version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t dschadow/client-info client-info
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push dschadow/client-info
artifacts:
  files:
    - client-info/target/client-info.jar