version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t dschadow/client-info client-info
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push dschadow/client-info
artifacts:
  files:
    - client-info/target/client-info.jar